=== osawa-koki/mandelbrot.java/config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="config">
  <xsd:complexType>
    <xsd:sequence>

      <xsd:element name="width" type="xsd:nonNegativeInteger" />
      <xsd:element name="height" type="xsd:nonNegativeInteger" />
      <xsd:element name="x_min" type="xsd:double" />
      <xsd:element name="x_max" type="xsd:double" />
      <xsd:element name="y_min" type="xsd:double" />
      <xsd:element name="y_max" type="xsd:double" />
      <xsd:element name="iteration" type="xsd:nonNegativeInteger" />
      <xsd:element name="threshold" type="xsd:nonNegativeInteger" />
      <xsd:element name="output" type="xsd:string" />

    </xsd:sequence>
  </xsd:complexType>
</xsd:element>
</xsd:schema>

=== osawa-koki/mandelbrot.java/config.xml
<?xml version="1.0" encoding="utf-8"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">

  <mandelbrot>
    <width>1024</width>
    <height>1024</height>
    <x_min>-2.5</x_min>
    <x_max>1.5</x_max>
    <y_min>-2.0</y_min>
    <y_max>2.0</y_max>
    <iteration>100</iteration>
    <incremental_step>100</incremental_step>
    <threshold>10</threshold>
    <output>mandelbrot1.png</output>
  </mandelbrot>

  <mandelbrot>
    <width>1024</width>
    <height>1024</height>
    <x_min>-2.5</x_min>
    <x_max>1.5</x_max>
    <y_min>-2.0</y_min>
    <y_max>2.0</y_max>
    <iteration>100</iteration>
    <incremental_step>100</incremental_step>
    <threshold>10</threshold>
    <output>mandelbrot2.png</output>
  </mandelbrot>

</config>
